services:
  - type: web
    name: video-to-sign-language
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PROJECT_URL
        sync: false
      - key: ANON_PUBLIC_KEY
        sync: false
    healthCheckPath: /health 